last_request_time = "2025-11-04 10:16:47"
update_interval_sec = 4544.270161290323

[usage]
remaining = 493
used = 7
last = 0

[sports]
all = true

[odds]
regions = "us"
markets = "h2h"
dateFormat = "iso"
oddsFormat = "decimal"
includeLinks = "true"
includeSids = "true"
