last_request_time = "2025-11-13 22:26:00"
update_interval_sec = 4206.2175226586105

[usage]
remaining = 329
used = 171
last = 0

[sports]
all = true

[odds]
regions = "us"
markets = "h2h"
dateFormat = "iso"
oddsFormat = "decimal"
includeLinks = "true"
includeSids = "true"
